name = "mos360-platform"
main = "src/worker.js"
compatibility_date = "2026-05-01"

[[kv_namespaces]]
binding = "MOS360_COURSES_KV"
id = "31110d6e2db34425accab5d6ae92ca46"

[[kv_namespaces]]
binding = "MOS360_TRACKING_KV"
id = "eee76ad74d4845458898a143a514ed84"

[vars]
JWT_SECRET = "MOS360_SECRET_KEY"
