name = "mos360-platform"
main = "src/worker.js"
compatibility_date = "2026-05-01"

[[kv_namespaces]]
binding = "MOS_COURSES"
id = "9f4d266d92784d749ceac0e8831adf70"

[[kv_namespaces]]
binding = "MOS360_TRACKING"
id = "eee76ad74d4845458898a143a514ed84"
